### ISSUE TITLE
Raw resources for recipes are computed wrong in nav view.

### ISSUE THREAD

**Issue by daviscook477** [EarendelDevelopers/factorio-mods#100]
Only in nav view.

Example is blue circuits.

![](https://cdn.discordapp.com/attachments/419527276875481111/842553238062497822/unknown.png)

**Comment by Derunih** [comment]
Can no longer replicate in nav view - Were there more prerequisites to get this to happen?

**Comment by daviscook477** [comment]
No. just going into nav view would make the raw resources compute wrong.

**Comment by Derunih** [comment]
Appears fixed from changes to intermediaries, like specifying which green chip recipe is to be used by default.
When tested against master, plates do get broken down into ores though, I am not sure if this is intended?

**Comment by Wiwiweb** [comment]
I believe this issue was due to recycling recipes.
The "total raw" count only uses recipes that the machine viewed can use, and so only goes down to whatever the machine can make.
Source: https://forums.factorio.com/viewtopic.php?t=4397
In the crafting screen, the "machine" is the character. The character can't manually use the recycling recipe so it worked ok. But in the navsat, you are a "god" controller with cheat mode on. You can technically use any recipe, and so Factorio was doing some weird loop.

I think the weird "you need 44 circuits to make 20 circuits" results are gone now that we set the recycling recipes to `allow_decomposition= false`.
There may still be some difference between character and navsat (e.g. the ore/plate difference you found. The navsat can use the furnace recipes so it goes down to ore, but the character can't so it only goes down to plate), but as long as it doesn't look crazy like the screenshot above, then it's fine imo.
