### ISSUE TITLE
SE: Let players hide negative priority zones from lists

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#128]
Lists such as Universe Explorer, and destination selection lists.
The setting should be player-specific, and either be a mod setting, or a checkbox somehwere in Universe Explorer. (Some design consideration is needed)

**Comment by InappropriatePenguin** [comment]
Should this setting also hide priority=0 surfaces? Otherwise, a player would have to manually modify priority on hundreds of surfaces by late game in order to keep their Universe explorer free of clutter.

If it _did_ hide priority=0 surfaces, it would certainly have to be a toggle in the Universe Explorer rather than a mod setting.

**Comment by InappropriatePenguin** [comment]
Added in 0.5.81.
