### ISSUE TITLE
How can i add support for another mods building to be built on space platform?

### ISSUE THREAD

**Issue by taori** [EarendelDevelopers/factorio-mods#179]
I posted the question on the official forums too, but i am afraid unless i just submit a PR implementing this may take a while.

This is the mod i am using

https://mods.factorio.com/mod/recursive-blueprints/discussion/61f2c601afd89b66ec663162

The mod introduces a building "blueprint deployer" which in general works while space exploration is active, but it cannot be built on space platform, so the functionality isn't usable in space.

**Comment by InappropriatePenguin** [comment]
You would just need to add `se_allow_in_space` = true to the prototype of the entity that you want to be buildable in space. That sort of thing is best to do in the mod itself, rather than in SE.

**Comment by taori** [comment]
Thanks a lot for the quick response. I'll get right to it then.

**Comment by InappropriatePenguin** [comment]
@taori, you're welcome :)

By the way, you'll want to add this property to the _entity_ rather than the item prototype as you've done, since it pertains to the entity directly. I'm not familiar with that mod's entities myself, but I suspect the file to look at will be prototypes/entity.lua.

I'll go ahead and close this issue. You can reopen if there's something that would need to be done on SE's end.
