### ISSUE TITLE
Spaceship loses flooring when launching from a specific planet.

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#192]
Search se-bug-reports for sarevockk and the submitted save file.

**Comment by InappropriatePenguin** [comment]
I looked into this.

The issue appears to stem from the player setting the width and height of their map (when they first created the game) as 1500 tiles. Their Nauvis looks like a square as a result, if you go to the map's edges.

More importantly though, those width and height values are part of `game.default_map_gen_settings`. While we set our own width and height when creating surfaces for space and solid SE zones, we are _not_ doing that for spaceships. That's why, for that particular player, spaceship surfaces were also getting created using the default width and height values of 1500 tiles.

When we launch a spaceship to its own surface, we use a clone_delta of `{dx=0, dy=0}`, such that entities and tiles are moved to their same positions but on the new spaceship surface. The spaceship the player was trying to launch, happened to be on coordinates that were out of bounds for a 1500x1500 surface, which was resulting in out-of-map tiles, and difficult-to-debug issues around chunk generation on the new spaceship surface. I believe this is what was making the spaceship floor tiles disappear.

This is fixed by specifying `width=0, height=0` in `map_gen_settings` when creating spaceship surfaces.

@Wiwiweb, should we perhaps warn the player if we detect that they set a mapgen width and/or height when starting a new game? They won't be having _this_ particular issue anymore, but they'll still wind up with a messed up Nauvis.

**Comment by Wiwiweb** [comment]
> @Wiwiweb, should we perhaps warn the player if we detect that they set a mapgen width and/or height when starting a new game? They won't be having this particular issue anymore, but they'll still wind up with a messed up Nauvis.

If we can, we should force those parameters to what we want (nil?). I don't see a reason to want to play on a square map.

With an exception for the 50x50 debug size.

**Comment by InappropriatePenguin** [comment]
We can't change `default_map_gen_settings` as they're read-only, though we can certainly modify Nauvis' map gen settings—I presume that's what you were saying. We'd want to set those parameter to 0 rather than nil, as nil would make the game use the default map gen settings and those are going to be whatever the player set in the new game screen.

I was thinking a warning might be sufficient, so that we don't stop someone determined to play in a ribbon-Nauvis or something. Changing width and height to something appropriate for Nauvis' radius would make sense too.
