### ISSUE TITLE
Incorrect production statistics

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#205]
spiral_power: "0.5.116, statistics is wrong. antimatter canister consumption is too low. each arcosphere collector consumes 10 antimatter canister. As I reported a long time ago, the fusion test data is also wrong."

**Comment by daviscook477** [comment]
it's definitely a catalyst issue. the antimatter canister is a catalyst in the arcosphere collector recipe (so it won't be tracked according to this post https://forums.factorio.com/viewtopic.php?f=23&t=66664&p=406556&hilit=catalyst+consumption#p406556)

Probably a similar thing is happening for the fusion test data since it is a catalyst in the recipe ingredients. It appears that any ingredient marked as a catalyst does not count in consumption stats, and any result marked as a catalyst does not count in production stats.

**Comment by spiralpower** [comment]
Hi, I'd like to post the multiple statistics issues I found in 0.6 somewhere. Is this the right place or is the discord better? There can be more than one cause.

**Comment by InappropriatePenguin** [comment]
@spiralpower, here would be fine.

**Comment by spiralpower** [comment]
Ok. First, I present the datas.
250h stable with 210 spm.

![1](https://user-images.githubusercontent.com/47108911/196346387-0ddeeadd-34ca-4bba-9471-6581f852973d.png)
Beryllium powder: prod < cons

![2](https://user-images.githubusercontent.com/47108911/196346966-822e2fcf-6872-43cb-99e7-2a10060101c4.png)
Holmium powder: prod < cons ( a bit, maybe )

![3](https://user-images.githubusercontent.com/47108911/196347120-d12ee598-8218-4a69-ba0f-5f988ed75b7d.png)
Iridium: powder: prod < cons
Iridite: prod < cons

![4](https://user-images.githubusercontent.com/47108911/196347375-2451e35d-01ad-442a-9678-e76ab54a0d6b.png)
Crushed vulcanite: prod > cons

![5](https://user-images.githubusercontent.com/47108911/196347557-36fedd91-1057-4958-a91c-bdd446c877a7.png)
Vitamelange spice: prod >> cons
Vitamelange extract: prod < cons

![11](https://user-images.githubusercontent.com/47108911/196350277-8a0356a3-fa82-4a90-a9d1-47373ca8c249.png)
Stone brick: prod < cons ( Possible measurement error, but noted just in case )

![6](https://user-images.githubusercontent.com/47108911/196347967-da6be535-a26d-445a-bd52-dd4edba27b10.png)
Sand: prod < cons

![7](https://user-images.githubusercontent.com/47108911/196348081-1561c764-61f5-4948-9f8b-34b2f9c15f88.png)
Naquim powder: prod > cons
Refined naquitite: prod > cons

![8](https://user-images.githubusercontent.com/47108911/196348555-269d1d99-3abb-49e8-9621-0a2c908d52aa.png)
Fusion test data: prod >> cons ( I posted before )

![9](https://user-images.githubusercontent.com/47108911/196349077-c2d99939-6e8e-497f-80da-f47e886c63e8.png)
Antimatter canister: prod >> cons ( I posted before )

![10](https://user-images.githubusercontent.com/47108911/196349684-8e328cb3-c3bc-4b4a-98e4-d727c761f5d5.png)
Steam: prod > cons ( Trivial difference, but even at 50h there is a 3k/m gap, so it may not be a measurement error )

**Comment by spiralpower** [comment]
prod < cons problem could be a case of below.
Negotiations with the factorio developers will be necessary, as it should be necessary to improve the factorio api in order to fix it.
https://forums.factorio.com/viewtopic.php?f=23&t=90157

**Comment by Wiwiweb** [comment]
All of the "prod < cons" are because at some point, a product is output as a "catalyst" to prevent it from being affected by productivity. But that has the side-effect of not counting that output in production graphs.
It's unfixable without Factorio giving us a way to mark an output as "not affected by prod" but still "counts in production graphs", as you've seen in that thread.

Going through the pictures:
* beryllium-powder: A catalyst output of the "naquium-refined" recipe.
* holmium-powder: A catalyst output of the "naquium-powder" recipe.
* iridium-powder: A catalyst output of the "naquium-ore-crushed" recipe.
* stone-brick: Not sure about this one... it's not delivery cannons.
* sand: Catalyst output in "cryonite-powder", "holmium-chloride", "iridium-powder", "vulcanite-enriched".
* antimatter-canister: I'll make the fill/empty recipes not count for stats (just like barrels) but in the end the number will still be unequal since raw canisters are sometimes consumed. That's normal.
* steam: Catalyst output in many recipes.

I can fix those: iridium, iridium-ore-crushed, vulcanite-crushed, vitamelange-spice, vitamelange-extract, naquium-powder, naquium-crushed.

**Comment by spiralpower** [comment]
Ah, thank you.
I am not so sure about stone brick.
How about this one.

Fusion test data: prod >> cons ( I posted before )

**Comment by spiralpower** [comment]
Thank you for fixing in 0.6.90.
It looks fine for the part that has been corrected.
Once my save is able to get 250 hours of stats, I will check the stats.

**Comment by spiralpower** [comment]
Here are the latest statistics in 0.6.90.
Those that have resolved the problem will not be listed.

![image](https://user-images.githubusercontent.com/47108911/202925318-711c5bf3-fd84-4b9b-b656-5d919be0a44f.png)
Beryllium powder: prod < cons

![image](https://user-images.githubusercontent.com/47108911/202925395-9f3439a0-62ad-4587-bc33-478ac5e02665.png)
Holmium powder: prod < cons ( a bit, maybe )

![image](https://user-images.githubusercontent.com/47108911/202925424-68b4ca01-46f1-4d3f-8a0e-c0bb67160b02.png)
Iridium: powder: prod < cons

![image](https://user-images.githubusercontent.com/47108911/202925574-a3c13069-9b97-4e1a-a228-9228fe0a2639.png)
Sand: prod < cons

![image](https://user-images.githubusercontent.com/47108911/202925691-5165dde5-d9ab-44e5-a79b-d3e690df1861.png)
![image](https://user-images.githubusercontent.com/47108911/202925698-bdea9808-25a2-4928-a12d-fed1c50dea91.png)
We may have a new problem.

![image](https://user-images.githubusercontent.com/47108911/202925736-3904e777-7588-4e96-9e75-98b95b90843d.png)
Steam: prod > cons

**Comment by Wiwiweb** [comment]
I'll be taking a look at each point in a bit.

**Comment by BurninSun** [comment]
I know fluids inside assembly machines get deleted on spaceship launch/landing. That might be where the steam is going.

**Comment by spiralpower** [comment]
I see, interesting story, but Internal turbine steam is prod = cons. 
Is it consistent?

**Comment by Wiwiweb** [comment]
> Beryllium powder: prod < cons

Can't be fixed. It's from the naquium-refined recipe which gives beryllium powder. We don't want the powder result to be affected by productivity here, and there's no way to say "not affected by productivity, but appears in production stats".

> Holmium powder: prod < cons

Same story but for the naquium-powder recipe.

> Sand: prod < cons

Same story, for a couple different recipes that output sand as a catalyst.

> Steam: prod > cons

Same story, probably from cryonite-crystal.

> Antimatter canisters

I'm gonna call that one intentional because we're copying the vanilla behaviour with barrels. You can't actually have a "water barrel" in your production graph. Similarily you won't be seeing antimatter canisters in production graph anymore. What's really produced is the antimatter.

**Comment by spiralpower** [comment]
> catalyst issue

https://forums.factorio.com/viewtopic.php?f=23&t=90157

I understand that this may be due to this problem, but as it is with the current factorio api, it is not possible to fix it with only mod-side implementation. Therefore, if possible, I hope to encourage improvements to the factorio api.
At least for me, statistical information is much, much more important and valuable than detailed assembly machine placement and the like.

> Antimatter canisters

I see, the Amtimatter stream used to match the left and right sides, but now they are different. However, there is something wrong with the canister gap not matching.

35M ≠ 4.7 * 1k

![image](https://user-images.githubusercontent.com/47108911/204957315-1e81e5b0-193f-494c-a5b7-88ced12a5265.png)
![image](https://user-images.githubusercontent.com/47108911/204957332-be4bbb3a-2f5a-4584-94c0-affcac8daa56.png)
![image](https://user-images.githubusercontent.com/47108911/204957724-53b6219a-6608-4c1d-8350-1f70770165e9.png)

**Comment by Wiwiweb** [comment]
Sorry I have to put this under "needs better API" too :D

Logically when a recipe consumes an antimatter canister and returns an empty canister, we should say "1000 antimatter was consumed" but there's no way to have a recipe give production/consumption for an unrelated item/fluid.

**Comment by spiralpower** [comment]
I see, I guess it means that there is no appropriate factorio api for antimatter at this time.

**Comment by InappropriatePenguin** [comment]
Are there any outstanding fixable issues or can this be closed?

**Comment by spiralpower** [comment]
I would like it to remain open as there are still unresolved issues, but what are your plans for future fixes?

**Comment by InappropriatePenguin** [comment]
If all of the unresolved issues require base-game changes, then there's no reason to keep this issue open. It's not like it will disappear. If Wube add functionality that allows them to be fixed (or other fixable issues are found), then it can be re-opened.

**Comment by spiralpower** [comment]
ok, thank you.
