### ISSUE TITLE
Stone Water Well no longer works in Editor's lab tiles

### ISSUE THREAD

**Issue by SpikesDivZero** [EarendelDevelopers/factorio-mods#210]
In Space Exploration 0.5, I could readily place a Stone Water Well on the Editor's lab tiles. Since upgrading to 0.6, this now reports "Cannot be built here". Specifically, the tiles in use are lab-dark-1 and lab-dark-2.

I'm aware that I can use the Infinite Pipe as a substitute in the meantime, but I'm filing this as I try to incorporate the position of wells in my designs, as I like my sub-factories to be neat and tidy, and being able to place the wells in the editor helps. :)

**Comment by Wiwiweb** [comment]
The problem is that Stone Water Well is defined as an offshore pump that needs to be placed "near ground".
To allow space entities on lab tiles we had to change the definition of lab tiles so that they are no longer "ground tiles".

To fix this you can modify the Stone Water Well code and add this:
```
waterwell.adjacent_tile_collision_test = {}
waterwell.fluid_box_tile_collision_test = {}
```
This shouldn't impact the normal usage of the wells.
