### ISSUE TITLE
Space capsules have an invisible entity which is attacked and destroyed by biters

### ISSUE THREAD

**Issue by BurninSun** [EarendelDevelopers/factorio-mods#212]
If a space capsule is placed (or landed) near biters, the biters will attack it. The result is a warning that a "space capsule" (regardless if it was the "compromised space capsule") is destroyed and the biters will then ignore it. However, the space capsule itself is still there and lootable by the player.

**Comment by InappropriatePenguin** [comment]
Yeah, upon taking a closer look, it turns out that biters were actually attacking the space capsule's _shadow_ of all things. They don't attack the vehicle because we set it to be indestructible, and they don't attack the container, I suspect, because it's not a military target and has no collision.

This appears to be solved by making the capsule container prototype a military target and  by making the capsule shadow indestructible upon creation, like the vehicle.

Welcome back.
