### ISSUE TITLE
Nanoengineering data has Superconductive instead of Holmium cables as a byproduct

### ISSUE THREAD

**Issue by TomyLobo** [EarendelDevelopers/factorio-mods#243]
I think this is a bug, since Nanoengineering data requires Superconductive cables neither directly nor indirectly.
The same is *not* true for the other byproducts.

**Comment by InappropriatePenguin** [comment]
Indeed, it seems like superconductive cables do not go into any of the ingredients. I'm leaning towards making holmium solenoid a 5% byproduct since it's worth a little more than holmium cables.

![Untitled](https://user-images.githubusercontent.com/72840021/212398533-0a0cf119-8614-495c-8468-c65bad78fd91.png)
