### ISSUE TITLE
Incompatibility between AAI containers and WideChests

### ISSUE THREAD

**Issue by Atria1234** [EarendelDevelopers/factorio-mods#354]
Both AAI Containers and WideChests modify `stack_size` of steel-chest, causing incompatibility.

Is it necessary to modify `stack_size` in AAI Containers? Wasn't same problem encountered in 1.1.*?

**Comment by Quezler** [comment]
AAI Containers always had a dropdown where the size tiers were selectable so i am assuming that meant it always overwrote it even back in 1.1, it is indeed surprising that the mods seemingly only started to conflict now.

**Comment by Wiwiweb** [comment]
It's an issue of load order.
In 1.1 aai-containers always loaded before WideChests because of mod names.
In 2.0 we added an optional dependency on space-age. So when playing with space-age, aai-containers, and WideChests, WideChests ends up loading before aai-containers.

I'll just tweak the way we set the stack size of chests.
