### ISSUE TITLE
Spaceship clamp wire connections

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#43]
Make an invisible power pole that sits over the back on the spaceship clamp. 

It should have a higher selection priority than the clamp so it is easier to select but the selection box should be smaller than the clamp (similar to spaceship output).

When a spaceship lands, check if clamps are facing and touching, if so connect the invisible poles with all 3 wire types.

The hidden poles should be part of blueprints, when a clamp is revived the hidden pole should get revived too so that the blueprinted connections are maintined.

**Comment by PeterRibbit** [comment]
While we're adding entities to the spaceship clamps, could we also add a rail segment? The clamps can be copypasted off the rail grid which leads to weird behavior - clamps appearing one space away from where they are acting.

**Comment by Alpha-Prime-01** [comment]
I would like to add a couple suggestions to the spaceship clamp update: 

-Make spaceship clamps in blueprints align to the train grid or simply, not allowed to be in a blueprint, copy/paste

Currently spaceship clamps will work with a yellow (output) arrows on both sides of connecting clamps, even with a blue input arrow signal going to the console. (the double yellow signals can lead to complications, although this specific outcome may have been fixed in the 'cant land on non-neutral entity update')
-Force spaceships to require a stationary clamp on a surface to have blue input clamp signals as well, this forcing could also be applied later during the 'mothership' update
-alternatively, do not allow spaceship clamps to change their own signal value, possibly a toggle from output (yellow) to input (blue) instead but have each clamp have a designated value on placement that cannot be altered (idea from Peace Bear0)

**Comment by daviscook477** [comment]
addressed by the PR I opened on top of atraxi's changes.
