### ISSUE TITLE
You can place water on a waterless planet if you die in the process.

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#71]
The normal event doesn't fire.
Possible solution is to search for water tiles on death if it is a waterless planet?

**Comment by daviscook477** [comment]
So from testing it looks like it's not possible to do this on the same tick the `on_pre_player_died` event is raised because no matter what I did, I could not set the tile at the player's death location. So to make this work, `on_pre_player_died` needs to raise `tick_task` for the following tick, on which it is possible to set the tiles in the region of the player's death to non-water tiles.
