### ISSUE TITLE
Spaceship Board feature has some weird exploits.

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#81]
There seems to be no sanity to how far away 2 ships can be for the "Board" feature to work.
1) Have 2 ships with eachother as destination meet up in interstellar space
2) Change the destination of the ship you're not inside of, while keeping the destination of the ship you're inside of, then send it away
3) Wait a while for the ship to go away
4) Now hit "Board" on the ship you're still inside of
5) You get teleported to the other ship despite it being several thousand dV away

**Comment by daviscook477** [comment]
The GUI doesn't seem to do an amazing job of responding to this scenario. but I can't reproduce the ability to board ships that aren't next to each other. since spaceship.lua now checks every time when the board button is clicked for if `Zone.get_travel_delta_v_sub(spaceship, othership) < 1` it won't ever let players board a ship that's far away unless that delta_v calculation is bugged.

So I think if this needs to be reopened it should be a calculation issue not a GUI one.
