### ISSUE TITLE
Big UPS drop when auto-glaving

### ISSUE THREAD

**Issue by jacobwatkinsgit** [EarendelDevelopers/factorio-mods#97]
Apologies in advance if I use some words / terms incorrectly, I am unfamiliar with the mod.

Link to someone's save:
https://drive.google.com/file/d/1KWH29DJbxX80EacVkDK2p2RnrHq_dyVG/view?usp=sharing

The UPS drop is coming from glaives firing. starting with the event:
scripts/energy-beam.lua
1) EnergyBeam.on_tick has transmitters/trees? to fire
2) EnergyBeam.beam_move is called
3) EnergyBeam.beam_move reaches `  if Util.vectors_delta_length(new_position, position) < 0.1 and tree.mode == "auto-glaive" then
    EnergyBeam.find_enemy(tree)
  end
`
4) EnergyBeam.find_enemy runs find_enemy
control.lua
5) find enemy doesn't have a performance problem, until   `local enemy = surface.find_nearest_enemy{position=position, max_distance=20000, force=force}` is executed (adding a do return end above it completely stops the performance issue...)

Thoughts: the vectors_delta_length may have problems, or the position isn't being stored properly after finding, because it doesn't make sense to go  < 0.1 and need to find an enemy again, every tick.

Other idea: store the enemy, and chase the enemy position (every tick, second, etc) until the entity is invalid or on another surface, and only then find a new enemy. If the position is reached and the entity is still alive... maybe delay a movement update. Thinking, this could be a cause for the lag: the position is met, but the entity survives, so every tick the glaive wants to move and kill something, but it keeps looking and finding one where it is.

**Comment by adugaue** [comment]
To add a little bit more context to this if it's not clear by the information above, the save file demonstrates how space-exploration-mod can spike between 15-40ms when this situation occurs and will continue cycling through this function indefinitely. The auto-glaiving on the save file had been running from roughly 20-30 hours without any issues until it started to run into the issue above when finding an enemy, in which case the map becomes almost unplayable.

Because of this, it can make determining the performance drop almost impossible by the typical means of uninstalling mods to troubleshoot since the situation can occur long after auto-glaiving is setup and forgotten. This was only found through using the debugger.

The save in the original post has the exact conditions setup for the huge UPS drop to occur, outside of normal auto-glaive conditions.

**Comment by adugaue** [comment]
It looks as though when there are no nests or worms to attack and it focuses on a single biter it constantly re-checks some kind of distance formula. The problem is exacerbated on modded biters because they take a really long time to kill. As soon as the beam is directly ontop of the biter UPS will severely tank. When the biter dies the UPS issue is resolved until it is ontop of another biter.
